### ISSUE TITLE
Add dark/light theme switcher

### ISSUE THREAD

**Issue by astagi** [jsonbinit/jsonbinit#2]
Create dark and light themes and add a switch to change the default theme.

**Comment by Aybee5** [comment]
Hello, I'll like to work on this

**Comment by astagi** [comment]
Sounds great @Aybee5 👍

**Comment by Aybee5** [comment]
So after cloning the project, I saw that the default background-color is dark. I'm going to create a light theme to the background-color and some elements

**Comment by astagi** [comment]
sounds good @Aybee5 we haven't provided multiple themes :)

**Comment by Aybee5** [comment]
#3 I created a PR

**Comment by astagi** [comment]
Thanks @Aybee5 I'll review it asap
